version: '3.8'

services:
  # Main application
  dental-app:
    build: .
    container_name: dental-clinic-app
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=dental_clinic
      - DB_USER=dental_user
      - DB_PASSWORD=dental_pass123
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN:-}
      - JAVA_OPTS=-Xms256m -Xmx512m
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - app_logs:/usr/local/tomcat/logs
      - ./backups:/backups
    restart: unless-stopped
    networks:
      - dental-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/RoleStaff/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: dental-clinic-db
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=dental_clinic
      - MYSQL_USER=dental_user
      - MYSQL_PASSWORD=dental_pass123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/dental_clinic.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./backups:/backups
    restart: unless-stopped
    networks:
      - dental-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "dental_user", "-pdental_pass123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    command: --default-authentication-plugin=mysql_native_password

  # Nginx Reverse Proxy (optional for SSL and load balancing)
  nginx:
    image: nginx:alpine
    container_name: dental-clinic-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - dental-app
    restart: unless-stopped
    networks:
      - dental-network
    profiles:
      - production  # Only start with --profile production

  # phpMyAdmin for database management (development only)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dental-clinic-phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_USER=dental_user
      - PMA_PASSWORD=dental_pass123
      - UPLOAD_LIMIT=100M
    ports:
      - "8081:80"
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - dental-network
    profiles:
      - development  # Only start with --profile development

  # Redis for caching (optional)
  redis:
    image: redis:alpine
    container_name: dental-clinic-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - dental-network
    profiles:
      - caching  # Only start with --profile caching

volumes:
  mysql_data:
    driver: local
  app_logs:
    driver: local
  nginx_logs:
    driver: local
  redis_data:
    driver: local

networks:
  dental-network:
    driver: bridge 